services:
  - type: static_site
    name: iwyn-portfolio
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

